agri-gaia/seerep

.github/workflows/main.yml
now they are  available for building of server when base is not rebuild
=> create ids in own step

examples/python/ROS/ROS_publishSimpleImage.py, examples/python/ROS/ROS_publishSimplePointcloud.py, examples/python/ROS/ROS_publishSimpleTF.py, examples/python/gRPC/simulated-data/loadSimulatedData.py, examples/python/gRPC/simulated-data/loadSimulatedDataWithInstancePosition.py, seerep-hdf5/seerep-hdf5-core/include/seerep-hdf5-core/hdf5-core-point-cloud.h, seerep-hdf5/seerep-hdf5-pb/include/seerep-hdf5-pb/hdf5-pb-pointcloud.h, seerep-hdf5/seerep-hdf5-pb/src/hdf5-pb-pointcloud.cpp, seerep-ros/seerep_ros_communication/include/seerep_ros_communication/client.h, seerep-ros/seerep_ros_communication/include/seerep_ros_communication/types.h, seerep-ros/seerep_ros_communication/launch/client.launch, seerep-ros/seerep_ros_communication/src/client.cpp, seerep-ros/seerep_ros_conversions_pb/include/seerep_ros_conversions_pb/conversions.h, seerep-ros/seerep_ros_conversions_pb/src/seerep_ros_conversions_pb/conversions.cpp, seerep-srv/seerep-core-pb/src/core-pb-pointcloud.cpp, seerep-srv/seerep-server/include/seerep-server/server.h, seerep-srv/seerep-server/src/pb-point-cloud-service.cpp, seerep-srv/seerep-server/src/server.cpp
This PR fixes multiple issues, including:
- Sending points clouds over gRPC with PB
- Sending images, tfs, and point clouds over ROS publisher Node (closes #171)
- Increasing the messages size of gRPC messages to 1GB
=> fix multiple issues with point clouds and ROS

.devcontainer/devcontainer.json
I found this [Doxygen extension](https://marketplace.visualstudio.com/items?itemName=cschlosser.doxdocgen) on the weekend, it seems useful for us.
=> add doxygen extension for vs-code

seerep-srv/seerep-core-fb/src/core-fb-image.cpp, seerep-srv/seerep-server/src/fb-image-service.cpp
in the addBoundingBox msg for images
=> check if any bounding boxes exist

seerep-com/CMakeLists.txt, seerep-msgs/CMakeLists.txt, seerep-msgs/cmake/BuildFlatBuffers.cmake
generate typescript flatbuffer files for the seerep-viewer.
=> feat: add -T to flatc for typescript files

examples/cpp/seerep_ros_communication/src/hdf5dump.cpp
Quick fix to catch the exceptions #215
=> catch exceptions from hdf5-io in ROS dumper 

examples/python/gRPC/images/gRPC_fb_queryImage.py, examples/python/gRPC/util_fb.py, seerep-hdf5/seerep-hdf5-core/src/hdf5-core-image.cpp, seerep-hdf5/seerep-hdf5-core/src/hdf5-core-point-cloud.cpp, seerep-hdf5/seerep-hdf5-core/src/hdf5-core-point.cpp, seerep-msgs/core/query.h, seerep-msgs/fbs/query.fbs, seerep-msgs/protos/query.proto, seerep-srv/seerep-core-fb/include/seerep-core-fb/core-fb-conversion.h, seerep-srv/seerep-core-fb/src/core-fb-conversion.cpp, seerep-srv/seerep-core-pb/include/seerep-core-pb/core-pb-conversion.h, seerep-srv/seerep-core-pb/src/core-pb-conversion.cpp, seerep-srv/seerep-core/include/seerep-core/core-dataset.h, seerep-srv/seerep-core/src/core-dataset.cpp
=> extend query for datasets having *all* of the defined labels and not just one of them

examples/python/gRPC/simulated-data/loadSimulatedData.py, seerep-hdf5/seerep-hdf5-core/src/hdf5-core-point-cloud.cpp, seerep-srv/seerep-core/include/seerep-core/core-tf.h, seerep-srv/seerep-core/src/core-tf.cpp
=> fix server crash due to wrong transformation of AABB

seerep-srv/seerep-server/include/seerep-server/server.h, seerep-srv/seerep-server/src/server.cpp
in addition to cmd and cfg file
=> parse environment vars

examples/python/gRPC/simulated-data/loadSimulatedDataWithInstancePosition.py, examples/python/gRPC/simulated-data/querySimulatedData.py, examples/python/gRPC/util_fb.py, seerep-hdf5/seerep-hdf5-core/src/hdf5-core-general.cpp
=> Fix simulated data scripts

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_general.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_general.cpp, seerep_msgs/core/project_info.h, seerep_msgs/fbs/project_info.fbs, seerep_msgs/protos/project_info.proto, seerep_srv/seerep_core/include/seerep_core/core_project.h, seerep_srv/seerep_core/src/core.cpp, seerep_srv/seerep_core/src/core_project.cpp, seerep_srv/seerep_server/src/fb_meta_operations.cpp, seerep_srv/seerep_server/src/pb_meta_operations.cpp
=> Save seerep version in hdf5 file

.github/workflows/test.yml
Changes:
- Run tests for each commit, to find bugs earlier. 
- Separate and parallelize the test steps into individual jobs. (Lowers runtime from ~6 min to ~4 min)
- Better overview if something failed, like here:
=> Update test action

.devcontainer/.vscode/launch.json
=> fix: vs code server startup config

examples/python/gRPC/pointcloud/gRPC_fb_sendPointCloud.py, examples/python/gRPC/util/fb_helper.py, seerep_hdf5/seerep_hdf5_fb/src/hdf5_fb_general.cpp, seerep_srv/seerep_server/src/fb_point_cloud_service.cpp
(+minor bug fixes while storing pointclouds)
=> extent sendPointCloud example by tf

examples/python/gRPC/images/gRPC_pb_addCameraIntrinsics.py, examples/python/gRPC/util/fb_helper.py, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_image.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_msgs/core/camera_intrinsics.h, seerep_msgs/fbs/camera_intrinsics.fbs, seerep_msgs/protos/camera_intrinsics.proto, seerep_srv/seerep_core/include/seerep_core/core_camera_intrinsics.h, seerep_srv/seerep_core/include/seerep_core/core_project.h, seerep_srv/seerep_core/src/core_camera_intrinsics.cpp, seerep_srv/seerep_core/src/core_project.cpp, seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp, seerep_srv/seerep_core_pb/src/core_pb_conversion.cpp, seerep_srv/seerep_server/src/fb_cameraintrinsics_service.cpp, seerep_srv/seerep_server/src/pb_camera_intrinsics_service.cpp
=> Frustrum Calculation

seerep_srv/seerep_core_fb/src/core_fb_image.cpp, seerep_srv/seerep_core_pb/src/core_pb_image.cpp
=> string gen instead of lexical cast camintrin uuid

examples/cpp/seerep_ros_communication/CMakeLists.txt, examples/cpp/seerep_ros_communication/include/seerep_ros_communication/rosbagDumper.h, examples/cpp/seerep_ros_communication/launch/rosbagDumper.launch, examples/cpp/seerep_ros_communication/package.xml, examples/cpp/seerep_ros_communication/src/rosbagDumper.cpp, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_cameraintrinsics.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_cameraintrinsics.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_msgs/core/camera_intrinsics.h, seerep_msgs/fbs/camera_intrinsics.fbs, seerep_msgs/protos/camera_intrinsics.proto, seerep_ros/seerep_ros_conversions_fb/CMakeLists.txt, seerep_ros/seerep_ros_conversions_fb/include/seerep_ros_conversions_fb/conversions.h, seerep_ros/seerep_ros_conversions_fb/package.xml, seerep_ros/seerep_ros_conversions_fb/src/seerep_ros_conversions_fb/conversions.cpp, seerep_srv/seerep_server/src/fb_meta_operations.cpp
(and debug cameraInfo in general)
=> add ros conversion for cameraInfo

examples/python/gRPC/util/fb_helper.py
Adds a function to fb_helper.py to retrieve name, uuid, frameid and geodetic_position of a project specefied by name.
=> Add getProjectInfo to fb_helper.py

examples/cpp/seerep_ros_communication/src/querier.cpp, seerep_msgs/core/query.h, seerep_msgs/fbs/query.fbs, seerep_msgs/protos/query.proto, seerep_srv/seerep_core/include/seerep_core/core_tf.h, seerep_srv/seerep_core/src/core_project.cpp, seerep_srv/seerep_core/src/core_tf.cpp, seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_conversion.h, seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp, seerep_srv/seerep_core_pb/include/seerep_core_pb/core_pb_conversion.h, seerep_srv/seerep_core_pb/src/core_pb_conversion.cpp, seerep_srv/seerep_server/src/fb_image_service.cpp, seerep_srv/seerep_server/src/fb_point_cloud_service.cpp, seerep_srv/seerep_server/src/fb_point_service.cpp, seerep_srv/seerep_server/src/pb_image_service.cpp, seerep_srv/seerep_server/src/pb_point_cloud_service.cpp
Bounding boxes are no longer in queries since we use polygons now.
=> Remove bb from query

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_general.h, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_tf.h, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/impl/hdf5_core_general.hpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_general.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_point.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_point_cloud.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_tf.cpp, seerep_hdf5/seerep_hdf5_fb/include/seerep_hdf5_fb/impl/hdf5_fb_general.hpp, seerep_hdf5/seerep_hdf5_pb/include/seerep_hdf5_pb/impl/hdf5_pb_general.hpp, seerep_srv/seerep_core/src/core_tf.cpp
=> Convert frame_ids which are not in specification with tf2

seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp, seerep_srv/seerep_core_pb/src/core_pb_conversion.cpp
=> label pb/fb to core remove the unique pointer

seerep_srv/seerep_server/src/fb_meta_operations.cpp, seerep_srv/seerep_server/src/pb_meta_operations.cpp
=> fix: adding all optional attributes to the project creation response

examples/python/gRPC/pointcloud/gRPC_fb_addBoundingBox.py, examples/python/gRPC/util/fb_helper.py, seerep_com/fbs/point_cloud_service.fbs, seerep_hdf5/seerep_hdf5_fb/include/seerep_hdf5_fb/hdf5_fb_pointcloud.h, seerep_hdf5/seerep_hdf5_fb/src/hdf5_fb_general.cpp, seerep_hdf5/seerep_hdf5_fb/src/hdf5_fb_pointcloud.cpp, seerep_msgs/CMakeLists.txt, seerep_msgs/fbs/boundingboxes_labeled_stamped.fbs, seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_pointcloud.h, seerep_srv/seerep_core_fb/src/core_fb_pointcloud.cpp, seerep_srv/seerep_server/include/seerep_server/fb_point_cloud_service.h, seerep_srv/seerep_server/src/fb_point_cloud_service.cpp
@Krause92
@mmeijerdfki: I added another python script
=> enable the later addition of bbs to point clouds

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_image.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_srv/seerep_core_fb/src/core_fb_image.cpp, seerep_srv/seerep_core_pb/src/core_pb_image.cpp
=> Add frustum calculation when adding images via gRPC

examples/python/gRPC/pointcloud/gRPC_fb_queryPointCloud.py, examples/python/gRPC/util/fb_helper.py
> [!NOTE]  
> Merge PR #354 first!
This PR contains:
- Refactor of the `gRPC_fb_queryPointCloud.py` example
- Decoding of received point clouds in numpy
=> Update FlatBuffers gRPC example to decode queried point clouds

docker/base/requirements.dev.txt, pyproject.toml
Fix dependabot alert due to CVE-2023-4785 and CVE-2023-4785
=> Bump grpcio package to 1.53.2

seerep_ros/seerep_ros_conversions_fb/src/seerep_ros_conversions_fb/conversions.cpp
Check data field for image conversion after a query withoutData.
=> check if image data is not empty
