docker/base/Dockerfile, examples/gRPC/images/gRPC_fb_queryImage.py, examples/gRPC/images/gRPC_pb_queryImage.py, examples/gRPC/images/gRPC_pb_queryImageGrid.py, examples/gRPC/images/gRPC_pb_sendLabeledImage.py, examples/gRPC/images/gRPC_pb_sendLabeledImageGrid.py
The `gRPC/` and `meta/` example scripts now work with the `testproject`. Also closes #93
=> fix example scripts

seerep-hdf5/seerep-hdf5-fb/test/fb-write-load-test.cpp
- Removed auto return types
- Added `seerep_hdf5_fb` and `tests` namespace
Closes #166
=> remove auto return type in seerep_hdf5_fb tests

seerep-hdf5/seerep-hdf5-fb/include/seerep-hdf5-fb/hdf5-fb-image.h, seerep-hdf5/seerep-hdf5-fb/include/seerep-hdf5-fb/hdf5-fb-point.h, seerep-hdf5/seerep-hdf5-fb/include/seerep-hdf5-fb/hdf5-fb-tf.h, seerep-hdf5/seerep-hdf5-fb/src/hdf5-fb-image.cpp, seerep-hdf5/seerep-hdf5-fb/src/hdf5-fb-point.cpp, seerep-hdf5/seerep-hdf5-fb/src/hdf5-fb-tf.cpp
Since I just changed the locations of the hdf5 definitions, everything should work as bevor. 
Closes #183
=> update fb to use hdf5 definitions from seerep-hdf5-core

.github/workflows/main.yml, docker/base/Dockerfile, docker/base/requirements.txt
- fixing incompatibly of the `protobuf==4.21.0` python package with `protoc<3.19.9`, by bumping protoc to `3.21.12`. Related: https://github.com/protocolbuffers/protobuf/issues/10051#
- Set versions for python packages in added `requirements.txt`, to prevent automatic updating
=> fix protoc incompatibility with latest protobuf python package

.devcontainer/devcontainer.json, docker/docker-compose.yml, seerep-srv/seerep-server/include/seerep-server/server.h, seerep-srv/seerep-server/src/server.cpp
The time(zone) in the docker container was not properly set. With this PR, the time will be retrieved from the host system via mounting the respective files.  This will only work for Unix based systems, I thought this was the most versatile way. We could also set the timezone explicitly, e.g. in the `docker-compose.yml` without a dependency on the host operating system: 
```.yml
version: "3.6"
services:
seerep:
image: ghcr.io/agri-gaia/seerep_server:latest
tty: true
container_name: seerep_server
command:
- "--data-folder=/mnt/seerep-data"
ports:
- 9090:9090
volumes:
#- /your/local/absolute/path:/mnt/seerep-data
- seerep-data:/mnt/seerep-data
environment:
- TZ=Europe/Berlin
volumes:
seerep-data:
```
=> Correct time(zone) in docker containers

docker/base/requirements.txt
Simple PR which bumps the NumPy version, to remove the [Dependabot alerts](https://github.com/agri-gaia/seerep/security/dependabot). Maybe you noticed the warnings in the git cli :sweat_smile:
=> Bump NumPy to fix vulnerabilities

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_general.h, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/impl/hdf5_core_general.hpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_general.cpp
The time functions deleted in this PR are obsolete, since we already provide generic function to read/write attributes from/to datasets or data groups: 
https://github.com/agri-gaia/seerep/blob/8b4f5d1a31086df502ba278e8fbca0dd3d30aa7a/seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/impl/hdf5_core_general.hpp#L5-L19
https://github.com/agri-gaia/seerep/blob/8b4f5d1a31086df502ba278e8fbca0dd3d30aa7a/seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/impl/hdf5_core_general.hpp#L21-L33
=> Remove unused core functions for time attributes

.isort.cfg, examples/python/gRPC/meta/gRPC_fb_loadProjects.py, examples/python/gRPC/util/fb_helper.py, seerep_com/fbs/meta_operations.fbs, seerep_srv/seerep_core/include/seerep_core/core.h, seerep_srv/seerep_core/src/core.cpp, seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_conversion.h, seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp, seerep_srv/seerep_server/include/seerep_server/fb_meta_operations.h, seerep_srv/seerep_server/src/fb_meta_operations.cpp
Summary:
- Return newly indexed projects when calling `LoadProjects` via gRPC
- Refactor `GetProjects` and `LoadProjects` 
- Python script to trigger the loading of the new projects
=> Return newly indexed projects from SEEREP core

docker/base/Dockerfile, docs/mkdocs/tutorials/images.md, examples/python/gRPC/images/gRPC_fb_queryImage.py, examples/python/gRPC/images/gRPC_fb_queryImageAndVisualize.py, examples/python/gRPC/images/gRPC_pb_queryImage.py, examples/python/gRPC/images/gRPC_pb_queryImageGrid.py, examples/python/gRPC/images/gRPC_pb_sendLabeledImageGrid.py, examples/python/gRPC/instances/gRPC_fb_getInstances.py, examples/python/gRPC/point/gRPC_fb_queryPoints.py, examples/python/gRPC/pointcloud/gRPC_fb_queryPointCloud.py, examples/python/gRPC/pointcloud/gRPC_fb_sendPointCloud.py, examples/python/gRPC/simulated-data/querySimulatedData.py, examples/python/gRPC/util/fb_helper.py, seerep_msgs/CMakeLists.txt, seerep_msgs/core/polygon2d.h, seerep_msgs/core/query.h, seerep_msgs/fbs/polygon2d.fbs, seerep_msgs/fbs/query.fbs, seerep_msgs/protos/polygon2d.proto, seerep_msgs/protos/query.proto, seerep_srv/seerep_core/CMakeLists.txt, seerep_srv/seerep_core/include/seerep_core/core_dataset.h, seerep_srv/seerep_core/src/core_dataset.cpp, seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_conversion.h, seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp, seerep_srv/seerep_core_pb/include/seerep_core_pb/core_pb_conversion.h, seerep_srv/seerep_core_pb/src/core_pb_conversion.cpp
Allow the user to query point cloud data using a polygon instead of a bounding box.
The Polygon has 2D vertices, along with a constant `z` value for all the points and a `height`. The z value defined the position of the 2D polygon along the z axis, and height defines how tall it is.
The user provides, along with this query, a boolean variable called `fullyEncapsulated`. If true, the results returned by the query must be entirely inside the provided polygon. The possibility of their not being fully inside the polygon arises due to the polygon's feature of being irregular. Being able to query irregular spaces (non axis aligned bb / oriented bb) is the principle contribution of this PR.
=> Polygon query

Doxyfile
Missed after changing the packages to ROS naming convention.
=> Fix doxygens list of searched directories after package renaming

seerep_srv/seerep_core/src/core_dataset.cpp
(spatial bounding box is a point)
Problem: if bounding box of dataset has no spatial extent, the polygon created based on this aabb has multiple point which are the same. Thus, the polygon isn't simple
Solution: only add one point to the "polygon" if the bounding box is just a point without spatial extent
=> enable the query of dataset with no spatial extent

seerep_hdf5/seerep_hdf5_pb/src/hdf5_pb_image.cpp
Bug: The calculation of the dataset size in `hdf5-pb` assumed that every image has 3 channels. 
Fix: Use the number of rows (height) times the size of each row in bytes for the calculation.
=> Fix calculation of image extension in hdf5-pb

.isort.cfg, docker/base/Dockerfile, docker/base/requirements.txt, examples/python/gRPC/pointcloud/gRPC_fb_queryPointCloud.py
This PR add as prompt for visualizing the queried point clouds (via FlatBuffers) using Open3D.
```
...
---Is dense--- 
True
---Payload--- 
[(0., 0., 0.,  3.,        0, 0,  0, 6338, 0)
(0., 0., 0., 10.,    96512, 0,  0, 6283, 0)
(0., 0., 0., 17.,   197120, 0,  0, 6189, 0) ...
(0., 0., 0.,  8., 99670528, 0, 63, 8333, 0)
(0., 0., 0., 14., 99764736, 0, 63, 8160, 0)
(0., 0., 0.,  1., 99857408, 0, 63, 8119, 0)]
------------
Visualize the point cloud? (Y/N) 
```
Example visualization:
=> Visualize queried point clouds using Open3D 

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_cameraintrinsics.h, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_general.h, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/impl/hdf5_core_general.hpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_cameraintrinsics.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_general.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_instance.cpp, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_tf.cpp, seerep_hdf5/seerep_hdf5_fb/include/seerep_hdf5_fb/impl/hdf5_fb_general.hpp, seerep_hdf5/seerep_hdf5_fb/src/hdf5_fb_pointcloud.cpp, seerep_hdf5/seerep_hdf5_pb/include/seerep_hdf5_pb/impl/hdf5_pb_general.hpp, seerep_srv/seerep_core/include/seerep_core/core.h, seerep_srv/seerep_core/include/seerep_core/core_camera_intrinsics.h, seerep_srv/seerep_core/include/seerep_core/core_project.h, seerep_srv/seerep_core/src/core.cpp, seerep_srv/seerep_core/src/core_camera_intrinsics.cpp, seerep_srv/seerep_core/src/core_project.cpp, seerep_srv/seerep_core_fb/src/core_fb_image.cpp, seerep_srv/seerep_core_pb/src/core_pb_image.cpp
PR for several small improvements in the `seerep_hdf5_core`  and `seerep_core` classes, which mainly involve:
- Removing unused code
- Renaming methods and variables to be more meaningful
- Refactoring methods by using already existing templates
=> Refactoring in seerep_hdf5_core and seerep_core

examples/python/gRPC/images/gRPC_fb_addCameraIntrinsics.py, examples/python/gRPC/images/gRPC_pb_addCameraIntrinsics.py, examples/python/gRPC/images/gRPC_pb_sendLabeledImage.py, seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_image.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_image.cpp, seerep_srv/seerep_core_fb/src/core_fb_image.cpp, seerep_srv/seerep_core_pb/src/core_pb_image.cpp, seerep_srv/seerep_server/include/seerep_server/fb_cameraintrinsics_service.h, seerep_srv/seerep_server/include/seerep_server/pb_camera_intrinsics_service.h, seerep_srv/seerep_server/include/seerep_server/service_constants.h, seerep_srv/seerep_server/src/fb_cameraintrinsics_service.cpp, seerep_srv/seerep_server/src/pb_camera_intrinsics_service.cpp
Closes #342. This also corrects a typo in Frustum.
Edit:
Empty values are now allowed, except for the intrinsics matrix.
=> Add check for the correct layout of camera intrinsics matrices.

.github/workflows/build-docs.yml, .github/workflows/buildDocker.yml, .github/workflows/gitlab-sync.yml, .github/workflows/main.yml, .github/workflows/test.yml, docker/base/requirements.txt, pyproject.toml
Includes:
- Updating actions to use node.js 20: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
- CVE-2023-51664 (tj-actions/changed-files)
- CVE-2023-1428, CVE-2023-32731, CVE-2023-32732 (gRPC)
=> Resolve deprecation and security warnings

docker/base/Dockerfile, seerep_srv/seerep_core/CMakeLists.txt, seerep_srv/seerep_core/src/core_project.cpp
Summary:
- Downgrade CMake to a version distributed with Ubuntu 20.04 due to incompatibilities with ROS noetic
- Fix CMake warnings generated by CGAL
- Remove unused dependencies from Docker base image
Some warnings will still be around:
```bash
warning: missing initializer for member ‘seerep_hdf5_core::ImageAttributes::cameraIntrinsicsUuid’ [-Wmissing-field-initializers]
```
`seerep_hdf5_py` has to be updated to support camera intrinsic #305
```bash
warning: unused parameter ‘options’ [-Wunused-parameter]
25 | std::unique_ptr< ImageService::Stub> ImageService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) 
...
```
The code is generated by `flatc`. Maybe updating to a more recent version would help? Something for a different PR.
=> Fix multiple CMake warnings

.github/workflows/test.yml, docker/server/Dockerfile
I forgot that ccache would already be included by the base image. Thus, installing it as another step causes problems when creating the symbolic links. 
Additionally, I also added the removal of the ccache cache after building the release, which saves around 100 MB in the final server image.
=> Fix ccache in CI

docker/server/docker-compose.yml
Was wondering all afternoon why the server wouldn't respond :expressionless:
Introduced by 0fb83ee16ae759223bbca0ed1a0ad1ca6a4c91b2, blame on me.
=> Fix: wrong docker image in server compose file

seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_image.h, seerep_srv/seerep_core_fb/src/core_fb_image.cpp, seerep_srv/seerep_server/src/fb_image_service.cpp
This is part of #350.
Changes:
- addData() for fb images is now split in two methods addDataToHdf5() and buildIndices()
- addDataToHdf5() only writes one image to hdf5
- When all images from a stream have been written to hdf5 buildIndices() can be called to create the indices for the by uuid specified projects and images
=> Defer index creation when storing images using the flatbuffers service

seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_pointcloud.h, seerep_srv/seerep_core_fb/src/core_fb_pointcloud.cpp, seerep_srv/seerep_server/src/fb_point_cloud_service.cpp
This is part of #350.
Changes:
- addData() for fb pointclouds is now split in two methods addDataToHdf5() and buildIndices()
- addDataToHdf5() only writes one pointcloud to hdf5
- When all pointclouds from a stream have been written to hdf5, buildIndices() can be called to create the indices for the by uuid specified projects and pointclouds
This lead to a improvement of roughly 15s in time to store 5000 pointclouds using the `gRPC_fb_sendPointCloud.py` script on my Intel® Core™ i5-8250U system, compared to the method before which took about 39s for that task.
=> Defer index creation when storing pointclouds using the flatbuffers service

docker/base/requirements.dev.txt
Upgrade Twine to resolve:
```
Traceback (most recent call last):
File "/usr/local/bin/twine", line 5, in <module>
from twine.__main__ import main
File "/usr/local/lib/python3.8/dist-packages/twine/__init__.py", line 43, in <module>
__license__ = metadata["license"]
File "/usr/local/lib/python3.8/dist-packages/importlib_metadata/_adapters.py", line 54, in __getitem__
raise KeyError(item)
KeyError: 'license'
```
=> upgrade twine to resolve KeyError: 'license'

.gitignore, seerep_com/cmake/ProtobufGenerateGrpcPython.cmake
This should fix the currently failing builds. Deprecation warnings will still be printed afterward.
A thorough description is in the commit message.
=> Fix: grpcio-tools not installed

seerep_srv/seerep_core_fb/include/seerep_core_fb/core_fb_point.h, seerep_srv/seerep_core_fb/src/core_fb_point.cpp, seerep_srv/seerep_server/src/fb_point_service.cpp
Closes #350.
Changes:
- addData() for fb point is now split in two methods addDataToHdf5() and buildIndices()
- addDataToHdf5() only writes the point data to hdf5
- When all points from a stream have been written to hdf5, buildIndices() can be called to create the indices for the by uuid specified projects and points
=> Defer index creation when storing points using the flatbuffers service

seerep_msgs/core/label.h, seerep_srv/seerep_core_fb/src/core_fb_conversion.cpp
- https://github.com/agri-gaia/seerep/commit/9a0b7822a33f2b86aaaf81d6357b58dc3f71b321 fixes the incorrect assignment of the `labelID` as the `instanceID` in the Flatbuffer core conversions
- https://github.com/agri-gaia/seerep/commit/b498056895370cae820cd722eb7d7be17913b824 adds default values to the core label message, otherwise an unset UUID will be interpreted as a valid `instanceID` that doesn't exist.
=> Fix minor bugs in the Datumaro integration

docs/mkdocs/reference/api.md, docs/mkdocs/tutorials/images.md, mkdocs.yml, seerep_com/README.md, seerep_com/fbs/README.md
Adds documentation about what services are available in FlatBuffers and Protocol Buffers and what messages they use. 
Preview:
=> docs: gRPC API documentation

seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_tf.h, seerep_hdf5/seerep_hdf5_core/src/hdf5_core_tf.cpp, seerep_hdf5/seerep_hdf5_ros/CMakeLists.txt, seerep_hdf5/seerep_hdf5_ros/include/seerep_hdf5_ros/hdf5_ros.h, seerep_hdf5/seerep_hdf5_ros/package.xml, seerep_hdf5/seerep_hdf5_ros/src/hdf5_ros.cpp, seerep_ros/seerep_ros_comm/CMakeLists.txt, seerep_ros/seerep_ros_comm/include/seerep_ros_comm/rostopic_dumper.h, seerep_ros/seerep_ros_comm/launch/rostopic_dumper.launch, seerep_ros/seerep_ros_comm/package.xml, seerep_ros/seerep_ros_comm/src/rostopic_dumper.cpp
- Refactor `seerep_hdf5_ros` package
- It now supports the storage of Images, CompressedImages, PointClouds and Transformations
- Stores transformations via common implementation in hdf5_core
Merge after #408
=> Refactor seerep_hdf5_ros

seerep_hdf5/seerep_hdf5_ros/include/seerep_hdf5_ros/hdf5_ros.h, seerep_hdf5/seerep_hdf5_ros/src/hdf5_ros.cpp
Fix dump of point clouds:
- Changed attribute names of point clouds by definition in class [Hdf5CorePointCloud](https://github.com/agri-gaia/seerep/blob/a4d4c0bcc63d16b0270688e9316e4c5e0412cc36/seerep_hdf5/seerep_hdf5_core/include/seerep_hdf5_core/hdf5_core_point_cloud.h).
- Compute bounding boxed directly in dump function based on [fb implementation](https://github.com/agri-gaia/seerep/blob/a4d4c0bcc63d16b0270688e9316e4c5e0412cc36/seerep_hdf5/seerep_hdf5_fb/src/hdf5_fb_pointcloud.cpp#L56).
=> Fixed names of pointcloud attributes and calculate bounding box
